interface Constants{
	double MARUTI_RESALE_PERCENT = (0.8);
	double HYUNDAI_RESALE_PERCENT = (0.6);
	double TOYOTA_RESALE_PERCENT = (0.4);
	int ADD_NEW_CUSTOMER = 1;
	int ADD_NEW_CAR_TO_EXISTING_CUSTOMER = 2;
	int LIST_OF_CUSTOMER =3;
	int DETAILS_OF_INDIVIDUAL_CUSTOMER = 4;
	int GENERATE_PRIZE =5;
	int MARUTI = 1;
	int HYUNDAI = 2;
	int TOYOTA = 3;
	int RANDOM_ID_LIMIT = 3;
	int RANDOM_GENERATED_IDS_LIMIT = 6;
}
